"use client";

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Info, Lightbulb, BrainCircuit } from "lucide-react";

export default function HelpPage() {
  return (
    <div className="container mx-auto max-w-4xl px-4 py-8 md:py-12">
      <div className="space-y-4 text-center">
        <h1 className="text-4xl font-bold tracking-tighter font-headline sm:text-5xl">
          Help & Frequently Asked Questions
        </h1>
        <p className="text-muted-foreground md:text-xl">
          Find answers to common questions about our tools.
        </p>
      </div>

      <div className="mt-12 space-y-8">
        <div>
          <h2 className="flex items-center mb-4 text-2xl font-bold font-headline">
            <Lightbulb className="mr-3 text-primary" />
            Business Model Recommender
          </h2>
          <Accordion type="single" collapsible className="w-full">
            <AccordionItem value="item-1">
              <AccordionTrigger>What is the Business Model Recommender?</AccordionTrigger>
              <AccordionContent>
                It's an AI-powered tool designed to help aspiring entrepreneurs and businesses. By filling out a detailed form about your business idea, the tool analyzes your input and suggests a suitable business model, potential MVP features, go-to-market strategies, and revenue forecasts.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="item-2">
              <AccordionTrigger>Is the business recommendation guaranteed to succeed?</AccordionTrigger>
              <AccordionContent>
                No. The recommendations are generated by an AI model based on the data you provide and patterns it has learned. It should be used as a starting point for your own research and planning. We strongly advise consulting with business professionals and conducting thorough market research before making financial decisions.
              </एन पीएम>
            </AccordionItem>
            <AccordionItem value="item-3">
              <AccordionTrigger>How is my data used?</AccordionTrigger>
              <AccordionContent>
                The information you enter into the form is used to generate the recommendation. Your form data is temporarily saved in your browser's local storage to prevent data loss but is cleared upon submission. We do not store your business criteria on our servers after the analysis is complete.
              </AccordionContent>
            </AccordionItem>
          </Accordion>
        </div>

        <div>
          <h2 className="flex items-center mb-4 text-2xl font-bold font-headline">
            <BrainCircuit className="mr-3 text-accent" />
            Check Yourself Tool
          </h2>
          <Accordion type="single" collapsible className="w-full">
            <AccordionItem value="item-1">
              <AccordionTrigger>What is the "Check Yourself" tool?</AccordionTrigger>
              <AccordionContent>
                This is a confidential and anonymous tool that allows you to answer a standardized mental health questionnaire (PHQ-9 for depression or GAD-7 for anxiety). Based on your answers, our AI provides a preliminary analysis, an estimated severity level, and general recommendations for next steps.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="item-2">
              <AccordionTrigger>Is this a medical diagnosis?</AccordionTrigger>
              <AccordionContent>
                <Alert variant="destructive" className="mb-4">
                  <Info className="h-4 w-4" />
                  <AlertTitle>This is NOT a diagnosis.</AlertTitle>
                  <AlertDescription>
                    The analysis provided is for informational and educational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment. You should always consult with a qualified healthcare provider for any health concerns.
                  </AlertDescription>
                </Alert>
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="item-3">
              <AccordionTrigger>Are my answers private?</AccordionTrigger>
              <AccordionContent>
                Yes. Your answers are completely anonymous. They are not stored on our servers or linked to you in any way. The information is processed to provide an immediate analysis and then discarded.
              </AccordionContent>
            </AccordionItem>
          </Accordion>
        </div>

        <div className="pt-8 text-center">
            <h3 className="font-headline text-xl font-semibold">Contact Us</h3>
            <p className="text-muted-foreground mt-2">
                For further questions, please reach out to <a href="mailto:support@claritycompass.com" className="text-primary underline">support@claritycompass.com</a>.
            </p>
        </div>
      </div>
    </div>
  );
}
